pure_pursuit_node:
  ros__parameters:
    drive_mode: "sim"

    odom_topic: "/localization/odom"
    path_topic: "/planning/path"

    sim_drive_topic: "/drive"

    real_speed_topic: "/commands/motor/speed"
    real_servo_topic: "/commands/servo/position"

    wheelbase: 0.33
    lookahead_distance: 1.0
    max_steering_angle: 0.4189

    target_speed: 1.0
    min_speed: 0.4
    max_speed: 2.0
    corner_slowdown_gain: 0.5

    kp: 1.0
    ki: 0.0
    kd: 0.05

    speed_to_erpm_gain: 3000.0
    speed_to_erpm_offset: 0.0

    servo_center: 0.5
    servo_gain: 1.0
    servo_min: 0.0
    servo_max: 1.0

    control_rate: 30.0
